'use client'

import { useState } from 'react'

const services = [
  { code: '01', title: 'Health Information System', text: 'SIMRS, SIM Klinik, SIM Puskesmas, dan sistem informasi kesehatan custom.', tone: 'teal' },
  { code: '02', title: 'Medical Record Management', text: 'Tracking berkas, ekspedisi digital, peminjaman, pengembalian, dan monitoring rekam medis.', tone: 'cyan' },
  { code: '03', title: 'Health Data & Statistics', text: 'Dashboard, statistik pelayanan, reporting, analytics, dan visualisasi data.', tone: 'blue' },
  { code: '04', title: 'Healthcare UI/UX', text: 'User flow, wireframe, UI design, prototype, dan usability improvement.', tone: 'lime' },
  { code: '05', title: 'Health IT Consulting', text: 'Analisis kebutuhan, workflow, digitalisasi, evaluasi sistem, dan strategi teknologi.', tone: 'orange' },
  { code: '06', title: 'Research & Development', text: 'R&D Digital Health, AI, rekam medis, interoperabilitas, data, dan teknologi kesehatan.', tone: 'pink' },
]

const facilities = ['Hospital', 'Clinic', 'Puskesmas', 'Independent Practice', 'Medical Record Unit', 'Laboratory']
const insights = ['Digital Health', 'Medical Records', 'RME', 'AI Healthcare', 'Healthcare UI/UX', 'Health Data']

function Arrow() { return <span aria-hidden="true">↗</span> }

function Ecosystem() {
  return (
    <div className="ecosystem" aria-label="Digital healthcare ecosystem visualization">
      <div className="orbit orbit-one" /><div className="orbit orbit-two" />
      <div className="network-line line-one" /><div className="network-line line-two" /><div className="network-line line-three" />
      <div className="core-node"><span>F</span><small>FANDORA<br />HEALTH OS</small></div>
      <div className="eco-card patient-card"><small>01 / PATIENT PROFILE</small><strong>Keisha M.</strong><span>•••• 4821</span><div className="mini-avatar">KM</div></div>
      <div className="eco-card record-card"><small>02 / MEDICAL RECORD</small><div className="record-row"><i /> <span>Clinical summary</span><b>98%</b></div><div className="record-row"><i /> <span>Visit history</span><b>12</b></div></div>
      <div className="eco-card analytics-card"><small>03 / HEALTHCARE DATA</small><div className="chart"><span /><span /><span /><span /><span /><span /><span /></div><div className="chart-label"><strong>+24.8%</strong><em>this month</em></div></div>
      <div className="eco-card flow-card"><small>04 / DIGITAL WORKFLOW</small><div className="flow-dots"><b>H</b><i>→</i><b>C</b><i>→</i><b>P</b></div><span>Connected facilities</span></div>
      <div className="node-label node-a">Hospital <b>●</b></div><div className="node-label node-b">Clinic <b>●</b></div><div className="node-label node-c">Analytics <b>●</b></div>
    </div>
  )
}

function DashboardMockup() {
  return <div className="dashboard-wrap"><div className="dashboard-glow" /><div className="dashboard">
    <div className="dash-side"><div className="dash-logo">F</div><span className="active" /><span /><span /><span /><span /></div>
    <div className="dash-main"><div className="dash-top"><div><small>MONDAY, 26 AUGUST 2026</small><h3>Good morning, Dr. Alvian</h3></div><div className="dash-avatar">RA</div></div><div className="stat-grid"><div><small>Total patients</small><strong>1,284</strong><em>+12.5%</em></div><div><small>Today&apos;s visits</small><strong>248</strong><em>+8.2%</em></div><div><small>Avg. waiting time</small><strong>18<span>m</span></strong><em className="down">-4.1%</em></div></div><div className="dash-content"><div className="big-chart"><div className="chart-head"><strong>Patient overview</strong><span>Last 7 days ▾</span></div><div className="bars"><i style={{height:'38%'}}/><i style={{height:'56%'}}/><i style={{height:'46%'}}/><i style={{height:'72%'}}/><i style={{height:'64%'}}/><i style={{height:'88%'}}/><i style={{height:'78%'}}/></div><div className="bar-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="activity"><strong>Recent activity</strong><div><b>RM</b><span><strong>RME updated</strong>Registration unit</span><small>09:42</small></div><div><b>QA</b><span><strong>Queue resolved</strong>Outpatient clinic</span><small>09:15</small></div><div><b>LP</b><span><strong>Report exported</strong>Medical record unit</span><small>08:54</small></div></div></div></div>
  </div><div className="floating-chip chip-top">● System health <b>99.9%</b></div><div className="floating-chip chip-bottom">⌁ Data synced <b>Just now</b></div></div>
}

export default function Page() {
  const [facility, setFacility] = useState('Hospital')
  const [sent, setSent] = useState(false)
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const message = `Halo Fandora, saya ${data.get('name')} dari ${data.get('institution')}. Saya ingin berkonsultasi tentang ${data.get('service')}. Kebutuhan saya: ${data.get('need')}`; setSent(true); window.open(`https://wa.me/6285746886318?text=${encodeURIComponent(message)}`, '_blank') }
  return <main>
    <nav className="nav container"><a className="brand" href="#top"><span>F</span> FANDORA</a><div className="nav-links"><a href="#services">Services</a><a href="#work">Selected work</a><a href="#insights">Insights</a></div><a className="nav-cta" href="#contact">Start a conversation <Arrow /></a></nav>
    <section id="top" className="hero"><div className="hero-grid" /><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> DIGITAL HEALTH TECHNOLOGY & HEALTH IT</div><h1>Transforming<br /><span>Healthcare</span> Through<br />Digital Technology.</h1><p>Fandora membantu rumah sakit, klinik, dan unit kesehatan mengubah proses manual menjadi layanan digital yang lebih aman, terukur, dan mudah dipakai—mulai dari rekam medis sampai analitik pelayanan.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Konsultasi Sekarang <Arrow /></a><a className="text-link" href="#work">Lihat Solusi <Arrow /></a></div><div className="hero-foot"><div><strong>Built around</strong><span>healthcare understanding</span></div><div className="hero-line" /><div><strong>Based in</strong><span>Indonesia · Remote ready</span></div></div></div><Ecosystem /></div><div className="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div></section>
    <section className="statement section"><div className="statement-inner container"><div className="section-kicker">THE DIGITAL HEALTH GAP</div><div className="statement-content"><h2>Healthcare is complex.<br /><span>Your technology shouldn&apos;t be.</span></h2><p>When data is fragmented and workflows are manual, the cost is felt everywhere. Fandora brings healthcare context and technology discipline together to make every decision clearer.</p></div><div className="problem-flow"><div><b>01</b><strong>Manual Process</strong><span>Slow, repetitive, prone to error</span></div><i>→</i><div><b>02</b><strong>Fragmented Data</strong><span>Information lives in silos</span></div><i>→</i><div><b>03</b><strong>Inefficient Workflow</strong><span>Teams work around systems</span></div><i>→</i><div className="problem-last"><b>04</b><strong>Limited Information</strong><span>Decisions lack context</span></div></div><div className="solution-flow"><div><b>01</b><strong>Digital Workflow</strong><span>Designed for how care happens</span></div><i>→</i><div><b>02</b><strong>Integrated Data</strong><span>One connected source of truth</span></div><i>→</i><div><b>03</b><strong>Efficient Process</strong><span>Less friction, more focus</span></div><i>→</i><div><b>04</b><strong>Actionable Insights</strong><span>Clarity when it matters</span></div></div></div></section>
    <section id="services" className="services-section section"><div className="container"><div className="section-head"><div><div className="section-kicker">WHAT WE DO</div><h2>Technology with<br /><span>healthcare context.</span></h2></div><p>Kami menerjemahkan kebutuhan klinis dan operasional menjadi sistem yang jelas: siapa melakukan apa, data bergerak ke mana, dan keputusan apa yang bisa dibuat lebih cepat.</p></div><div className="service-grid">{services.map(s => <article className={`service-card ${s.tone}`} key={s.code}><div className="service-top"><small>{s.code}</small><div className="service-icon">{s.code === '01' ? '⌘' : s.code === '02' ? '▣' : s.code === '03' ? '⌁' : s.code === '04' ? '✦' : s.code === '05' ? '◈' : '◎'}</div></div><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Explore service <Arrow /></a></article>)}</div></div></section>
    <section id="work" className="showcase section responsive-showcase"><div className="container"><div className="section-kicker">A GLIMPSE INTO THE FUTURE</div><div className="showcase-head"><h2>Technology designed<br /><span>around healthcare.</span></h2><p>Interfaces that make complex systems feel simple, calm, and ready for the people who use them every day.</p></div><DashboardMockup /><div className="showcase-caption"><strong>Fandora Health OS</strong><span>One connected view for every layer of your healthcare operation.</span><a href="#contact">See how it works <Arrow /></a></div></div></section>
    <section className="process section"><div className="container"><div className="section-kicker">HOW WE WORK</div><div className="process-head"><h2>From complexity<br /><span>to clarity.</span></h2><p>A deliberate process. No black boxes. Every step built around your team and your goals.</p></div><div className="process-line" /> <div className="process-grid">{['Discovery','Analysis','UI / UX','Development','Implementation','Improvement'].map((x,i) => <div key={x} className="process-step"><b>0{i+1}</b><span className="process-dot" /><h3>{x}</h3><p>{['Listen deeply. Understand the need behind the need.','Map the current state and find opportunities.','Make the invisible workflow visible and intuitive.','Build with care, test with the people who use it.','Support adoption and make change feel natural.','Learn, iterate, and keep making it better.'][i]}</p></div>)}</div></div></section>
    <section className="portfolio section container"><div className="section-kicker">SELECTED WORK / CONCEPTS</div><div className="section-head"><h2>Systems that make<br /><span>an impact.</span></h2><p>Selected explorations in health information systems, data, and digital experiences.</p></div><div className="portfolio-grid"><article className="portfolio-main"><div className="portfolio-art art-qmed"><div className="qmed-top"><span>Q-MED</span><small>QUEUE MANAGEMENT SYSTEM</small></div><div className="queue-number">04<span>Patients waiting</span></div><div className="queue-row"><b>A-021</b><span>General Clinic</span><em>Now serving</em></div><div className="queue-row"><b>A-022</b><span>General Clinic</span><em>Next</em></div></div><div className="portfolio-meta"><div><small>01 / SYSTEM DESIGN</small><h3>Q-MED</h3><span>Queue Medical System</span></div><a href="#contact">View project <Arrow /></a></div></article><article className="portfolio-side"><div className="portfolio-art art-record"><div className="record-header">MEDICAL RECORD <b>•••</b></div><div className="record-person"><div>AS</div><span><b>Andi Saputra</b>Patient · 34 years</span></div><div className="record-line long" /><div className="record-line" /><div className="record-line short" /></div><div className="portfolio-meta"><div><small>02 / DIGITAL WORKFLOW</small><h3>Medical Record Management</h3></div><a href="#contact">View project <Arrow /></a></div></article><article className="portfolio-side"><div className="portfolio-art art-stats"><small>HEALTHCARE STATISTICS</small><strong>78.4%</strong><span>Service efficiency</span><div className="stats-curve" /></div><div className="portfolio-meta"><div><small>03 / DATA VISUALIZATION</small><h3>Healthcare Statistics System</h3></div><a href="#contact">View project <Arrow /></a></div></article></div></section>
    <section className="trust section"><div className="container trust-grid"><div><div className="section-kicker">THE FANDORA DIFFERENCE</div><h2>Built with<br /><span>understanding.</span></h2><p>Good health technology is not just about the technology. It is about understanding the human system around it.</p></div><div className="equation"><div className="eq-items"><span>Healthcare<br /><b>Knowledge</b></span><i>+</i><span>Technology</span><i>+</i><span>Data</span><i>+</i><span>UI / UX</span><i>+</i><span>Research</span></div><div className="eq-line" /><strong>Digital Health <em>Solution</em></strong></div></div></section>
    <section id="insights" className="insights section container"><div className="section-head"><div><div className="section-kicker">FROM THE FIELD</div><h2>Ideas for a<br /><span>healthier digital future.</span></h2></div><a className="text-link" href="#contact">View all insights <Arrow /></a></div><div className="insight-grid">{insights.map((x,i) => <article className={`insight-card insight-${i}`} key={x}><div className="insight-art"><div className="insight-lines"></div></div><small>INSIGHT / {x.toUpperCase()}</small><h3>{['Why digital health projects fail before they begin','The quiet power of a well-designed medical record','RME is more than compliance. It is continuity.','Where AI meets the everyday healthcare workflow','Designing calm into complex health systems','From raw numbers to better decisions'][i]}</h3><a href="#contact">Read insight <Arrow /></a></article>)}</div></section>
    <section id="contact" className="contact section"><div className="contact-grid" /><div className="container contact-inner"><div className="contact-copy"><div className="section-kicker">LET&apos;S MAKE IT BETTER</div><h2>Have a healthcare<br />problem you want<br /><span>to digitize?</span></h2><p>Ceritakan kebutuhan Anda. Mari eksplorasi solusi digital yang tepat untuk fasilitas dan workflow Anda.</p><div className="contact-direct"><a href="https://wa.me/6285746886318">WhatsApp <Arrow /><small>0857 4688 6318</small></a><a href="mailto:rifkialvianchilmi@gmail.com">Email <Arrow /><small>rifkialvianchilmi@gmail.com</small></a></div></div><form className="contact-form" onSubmit={submit}><div className="form-row"><label>Nama<input name="name" placeholder="Nama lengkap" required /></label><label>Institusi<input name="institution" placeholder="Nama institusi" required /></label></div><div className="form-row"><label>Email<input name="email" type="email" placeholder="email@institusi.com" required /></label><label>WhatsApp<input name="whatsapp" placeholder="0857..." required /></label></div><label>Jenis fasilitas<select name="facility" defaultValue="Hospital">{facilities.map(x => <option key={x}>{x}</option>)}</select></label><label>Layanan yang dibutuhkan<select name="service" defaultValue={services[0].title}>{services.map(x => <option key={x.code}>{x.title}</option>)}</select></label><label>Kebutuhan Anda<textarea name="need" placeholder="Ceritakan sedikit tentang tantangan yang ingin diselesaikan..." rows={3} required /></label><button className="button button-primary" type="submit">{sent ? 'Pesan siap dikirim' : 'Kirim Konsultasi'} <Arrow /></button><small className="form-note">Dengan mengirim form, Anda akan diarahkan ke WhatsApp Fandora.</small></form></div></section>
    <footer className="footer container"><div className="brand"><span>F</span> FANDORA</div><p>Digital Health Technology<br />& Health IT Consultant</p><div className="footer-right"><span>© 2026 Fandora. Built around care.</span><a href="mailto:rifkialvianchilmi@gmail.com">rifkialvianchilmi@gmail.com</a></div></footer><a className="whatsapp" href="https://wa.me/6285746886318" aria-label="Chat on WhatsApp"><span>◔</span><i /></a>
  </main>
}
